import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { Product } from '../models/Product.js';

dotenv.config();

export const akijFantasticProducts = [
  {
    sku: 'AK-01',
    name: 'Nice 36gm',
    banglaName: 'নাইস ৩৬ গ্রাম',
    category: 'Biscuits',
    cartonSize: 48,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 480,
    minStockAlert: 96,
  },
  {
    sku: 'AK-02',
    name: 'Ghee Cake',
    banglaName: 'ঘি কেক',
    category: 'Cakes',
    cartonSize: 24,
    dealerPrice: 28.0,
    tradePrice: 32.0,
    mrp: 35,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-03',
    name: 'Fun Fest Box- ATC-738gm',
    banglaName: 'ফান ফেস্ট বক্স ৭৩৮ গ্রাম',
    category: 'Gift & Festival Packs',
    cartonSize: 8,
    dealerPrice: 220.0,
    tradePrice: 250.0,
    mrp: 280,
    currentStockPcs: 64,
    minStockAlert: 16,
  },
  {
    sku: 'AK-04',
    name: 'Funtastic Hebby Energy 104gm',
    banglaName: 'ফ্যান্টাস্টিক হেব্বি এনার্জি ১০৪ গ্রাম',
    category: 'Energy Biscuits',
    cartonSize: 36,
    dealerPrice: 16.5,
    tradePrice: 18.0,
    mrp: 20,
    currentStockPcs: 360,
    minStockAlert: 72,
  },
  {
    sku: 'AK-05',
    name: 'Funtastic Hebby Energy-40gm',
    banglaName: 'ফ্যান্টাস্টিক হেব্বি এনার্জি ৪০ গ্রাম',
    category: 'Energy Biscuits',
    cartonSize: 60,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 600,
    minStockAlert: 120,
  },
  {
    sku: 'AK-06',
    name: 'Funtastic Hebby Energy Tiffin 16gm',
    banglaName: 'ফ্যান্টাস্টিক হেব্বি এনার্জি টিফিন ১৬ গ্রাম',
    category: 'Energy Biscuits',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-07',
    name: 'Funtastic Lexus Biscuit-15gm',
    banglaName: 'ফ্যান্টাস্টিক লেক্সাস বিস্কুট ১৫ গ্রাম',
    category: 'Crackers & Salty',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-08',
    name: 'Funtastic Lexus Biscuit-180gm',
    banglaName: 'ফ্যান্টাস্টিক লেক্সাস বিস্কুট ১৮০ গ্রাম',
    category: 'Crackers & Salty',
    cartonSize: 24,
    dealerPrice: 37.0,
    tradePrice: 40.0,
    mrp: 45,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-09',
    name: 'Funtastic Lexus Biscuit-36gm',
    banglaName: 'ফ্যান্টাস্টিক লেক্সাস বিস্কুট ৩৬ গ্রাম',
    category: 'Crackers & Salty',
    cartonSize: 60,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 600,
    minStockAlert: 120,
  },
  {
    sku: 'AK-10',
    name: 'Funtastic Sweet Toast-250gm',
    banglaName: 'ফ্যান্টাস্টিক সুইট টোস্ট ২৫০ গ্রাম',
    category: 'Toast & Dry Cake',
    cartonSize: 16,
    dealerPrice: 41.0,
    tradePrice: 45.0,
    mrp: 50,
    currentStockPcs: 160,
    minStockAlert: 32,
  },
  {
    sku: 'AK-11',
    name: 'Glaze-Family-180gm',
    banglaName: 'গ্লেজ ফ্যামিলি ১৮০ গ্রাম',
    category: 'Cookies',
    cartonSize: 24,
    dealerPrice: 37.0,
    tradePrice: 40.0,
    mrp: 45,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-12',
    name: 'Glaze-Mini-16gm',
    banglaName: 'গ্লেজ মিনি ১৬ গ্রাম',
    category: 'Cookies',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-13',
    name: 'Glaze-Standard-40gm',
    banglaName: 'গ্লেজ স্ট্যান্ডার্ড ৪০ গ্রাম',
    category: 'Cookies',
    cartonSize: 60,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 600,
    minStockAlert: 120,
  },
  {
    sku: 'AK-14',
    name: 'Milk Mate-42gm',
    banglaName: 'মিল্ক মেট ৪২ গ্রাম',
    category: 'Milk Biscuits',
    cartonSize: 48,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 480,
    minStockAlert: 96,
  },
  {
    sku: 'AK-15',
    name: 'Milk Mate-Family-203gm',
    banglaName: 'মিল্ক মেট ফ্যামিলি ২০৩ গ্রাম',
    category: 'Milk Biscuits',
    cartonSize: 20,
    dealerPrice: 41.0,
    tradePrice: 45.0,
    mrp: 50,
    currentStockPcs: 200,
    minStockAlert: 40,
  },
  {
    sku: 'AK-16',
    name: 'Milk Mate-Mini-19gm',
    banglaName: 'মিল্ক মেট মিনি ১৯ গ্রাম',
    category: 'Milk Biscuits',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-17',
    name: 'Nimok Halal-180gm',
    banglaName: 'নিমতক হালাল ১৮০ গ্রাম',
    category: 'Crackers & Salty',
    cartonSize: 24,
    dealerPrice: 37.0,
    tradePrice: 40.0,
    mrp: 45,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-18',
    name: 'Nimok Halal-19gm',
    banglaName: 'নিমক হালাল ১৯ গ্রাম',
    category: 'Crackers & Salty',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-19',
    name: 'Nimok Halal-83gm',
    banglaName: 'নিমক হালাল ৮৩ গ্রাম',
    category: 'Crackers & Salty',
    cartonSize: 36,
    dealerPrice: 16.5,
    tradePrice: 18.0,
    mrp: 20,
    currentStockPcs: 360,
    minStockAlert: 72,
  },
  {
    sku: 'AK-20',
    name: 'Ore Cream Chocolate-15gm',
    banglaName: 'ওরে ক্রিম চকলেট ১৫ গ্রাম',
    category: 'Cream Biscuits',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-21',
    name: 'Ore Cream Chocolate-165gm',
    banglaName: 'ওরে ক্রিম চকলেট ১৬৫ গ্রাম',
    category: 'Cream Biscuits',
    cartonSize: 24,
    dealerPrice: 45.0,
    tradePrice: 50.0,
    mrp: 55,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-22',
    name: 'Ore Cream Chocolate-35gm',
    banglaName: 'ওরে ক্রিম চকলেট ৩৫ গ্রাম',
    category: 'Cream Biscuits',
    cartonSize: 48,
    dealerPrice: 8.5,
    tradePrice: 9.5,
    mrp: 10,
    currentStockPcs: 480,
    minStockAlert: 96,
  },
  {
    sku: 'AK-23',
    name: 'Toast-Family-185gm',
    banglaName: 'টোস্ট ফ্যামিলি ১৮৫ গ্রাম',
    category: 'Toast & Dry Cake',
    cartonSize: 20,
    dealerPrice: 32.0,
    tradePrice: 36.0,
    mrp: 40,
    currentStockPcs: 200,
    minStockAlert: 40,
  },
  {
    sku: 'AK-24',
    name: 'Funtastic Elachi Biscuit-42gm',
    banglaName: 'ফ্যান্টাস্টিক এলাচি বিস্কুট ৪২ গ্রাম',
    category: 'Biscuits',
    cartonSize: 48,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 480,
    minStockAlert: 96,
  },
  {
    sku: 'AK-25',
    name: "Bakeman's Nice 17gm",
    banglaName: 'বেকম্যান্স নাইস ১৭ গ্রাম',
    category: 'Biscuits',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-26',
    name: "Bakeman's Bahtar Butter Cookies 66gm",
    banglaName: 'বেকম্যান্স বাহতার বাটার কুকিজ ৬৬ গ্রাম',
    category: 'Cookies',
    cartonSize: 36,
    dealerPrice: 13.0,
    tradePrice: 14.5,
    mrp: 15,
    currentStockPcs: 360,
    minStockAlert: 72,
  },
  {
    sku: 'AK-27',
    name: "Bakeman's Coconut Craze Cookies 66gm",
    banglaName: 'বেকম্যান্স কোকোনাট ক্রেজ কুকিজ ৬৬ গ্রাম',
    category: 'Cookies',
    cartonSize: 36,
    dealerPrice: 13.0,
    tradePrice: 14.5,
    mrp: 15,
    currentStockPcs: 360,
    minStockAlert: 72,
  },
  {
    sku: 'AK-28',
    name: 'Choco Boost-Standard-72gm',
    banglaName: 'চকো বুস্ট স্ট্যান্ডার্ড ৭২ গ্রাম',
    category: 'Cookies',
    cartonSize: 36,
    dealerPrice: 17.0,
    tradePrice: 19.0,
    mrp: 20,
    currentStockPcs: 360,
    minStockAlert: 72,
  },
  {
    sku: 'AK-29',
    name: "Bakeman's Coconut Craze170gm",
    banglaName: 'বেকম্যান্স কোকোনাট ক্রেজ ১৭০ গ্রাম',
    category: 'Cookies',
    cartonSize: 24,
    dealerPrice: 37.0,
    tradePrice: 41.0,
    mrp: 45,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-30',
    name: "Bakeman's Bahtar 170gm",
    banglaName: 'বেকম্যান্স বাহতার ১৭০ গ্রাম',
    category: 'Cookies',
    cartonSize: 24,
    dealerPrice: 37.0,
    tradePrice: 41.0,
    mrp: 45,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-31',
    name: 'Choco Boost (204gm)',
    banglaName: 'চকো বুস্ট ২০৪ গ্রাম',
    category: 'Cookies',
    cartonSize: 18,
    dealerPrice: 50.0,
    tradePrice: 55.0,
    mrp: 60,
    currentStockPcs: 180,
    minStockAlert: 36,
  },
  {
    sku: 'AK-32',
    name: 'Funtastic Chocolate Pound Cake-67gm',
    banglaName: 'ফ্যান্টাস্টিক চকলেট পাউন্ড কেক ৬৭ গ্রাম',
    category: 'Cakes',
    cartonSize: 24,
    dealerPrice: 21.0,
    tradePrice: 23.0,
    mrp: 25,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-33',
    name: 'Funtastic Milky Butter Cup Cake-10gm',
    banglaName: 'ফ্যান্টাস্টিক মিল্কি বাটার কাপ কেক ১০ গ্রাম',
    category: 'Cakes',
    cartonSize: 72,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 720,
    minStockAlert: 144,
  },
  {
    sku: 'AK-34',
    name: 'Funtastic Milky Butter Pound Cake-67gm',
    banglaName: 'ফ্যান্টাস্টিক মিল্কি বাটার পাউন্ড কেক ৬৭ গ্রাম',
    category: 'Cakes',
    cartonSize: 24,
    dealerPrice: 21.0,
    tradePrice: 23.0,
    mrp: 25,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-35',
    name: 'Funtastic Mixed Fruit Pound Cake-70gm',
    banglaName: 'ফ্যান্টাস্টিক মিক্সড ফ্রুট পাউন্ড কেক ৭০ গ্রাম',
    category: 'Cakes',
    cartonSize: 24,
    dealerPrice: 22.0,
    tradePrice: 24.0,
    mrp: 25,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-36',
    name: 'Funtastic Vanilla Cream Filled Cup Cake-18gm',
    banglaName: 'ফ্যান্টাস্টিক ভ্যানিলা ক্রিম কাপ কেক ১৮ গ্রাম',
    category: 'Cakes',
    cartonSize: 48,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 480,
    minStockAlert: 96,
  },
  {
    sku: 'AK-37',
    name: 'Funtastic Vanilla Plain Cup-10gm',
    banglaName: 'ফ্যান্টাস্টিক ভ্যানিলা প্লেন কাপ ১০ গ্রাম',
    category: 'Cakes',
    cartonSize: 72,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 720,
    minStockAlert: 144,
  },
  {
    sku: 'AK-38',
    name: 'Funtastic Vanilla Pound Cake-67gm',
    banglaName: 'ফ্যান্টাস্টিক ভ্যানিলা পাউন্ড কেক ৬৭ গ্রাম',
    category: 'Cakes',
    cartonSize: 24,
    dealerPrice: 21.0,
    tradePrice: 23.0,
    mrp: 25,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-39',
    name: 'Layer Cake Vanilla-Chain-17gm',
    banglaName: 'লেয়ার কেক ভ্যানিলা চেইন ১৭ গ্রাম',
    category: 'Cakes',
    cartonSize: 72,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 720,
    minStockAlert: 144,
  },
  {
    sku: 'AK-40',
    name: 'Layer Cake Vanilla-Chain-8gm',
    banglaName: 'লেয়ার কেক ভ্যানিলা চেইন ৮ গ্রাম',
    category: 'Cakes',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-41',
    name: 'Pie Cake Chocolate Chain-18gm',
    banglaName: 'পাই কেক চকলেট চেইন ১৮ গ্রাম',
    category: 'Cakes',
    cartonSize: 72,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 720,
    minStockAlert: 144,
  },
  {
    sku: 'AK-42',
    name: 'YUM Chocolate Muffin Cake (17gm)',
    banglaName: 'ইয়াম চকলেট মাফিন কেক ১৭ গ্রাম',
    category: 'Cakes',
    cartonSize: 60,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 600,
    minStockAlert: 120,
  },
  {
    sku: 'AK-43',
    name: 'Yum Dry Cake-24gm',
    banglaName: 'ইয়াম ড্রাই কেক ২৪ গ্রাম',
    category: 'Toast & Dry Cake',
    cartonSize: 60,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 600,
    minStockAlert: 120,
  },
  {
    sku: 'AK-44',
    name: 'Yum Strawberry Swiss Roll-30gm',
    banglaName: 'ইয়াম স্ট্রবেরি সুইস রোল ৩০ গ্রাম',
    category: 'Cakes',
    cartonSize: 48,
    dealerPrice: 12.5,
    tradePrice: 14.0,
    mrp: 15,
    currentStockPcs: 480,
    minStockAlert: 96,
  },
  {
    sku: 'AK-45',
    name: 'Funtastic Vanilla Pound Cake 190gm',
    banglaName: 'ফ্যান্টাস্টিক ভ্যানিলা পাউন্ড কেক ১৯০ গ্রাম',
    category: 'Cakes',
    cartonSize: 16,
    dealerPrice: 58.0,
    tradePrice: 65.0,
    mrp: 70,
    currentStockPcs: 160,
    minStockAlert: 32,
  },
  {
    sku: 'AK-46',
    name: 'Hi5 Chocolate coated wafer-Ind-320gm',
    banglaName: 'হাই ফাইভ চকলেট কোটেড ওয়েফার ৩২০ গ্রাম',
    category: 'Wafers & Rolls',
    cartonSize: 12,
    dealerPrice: 85.0,
    tradePrice: 95.0,
    mrp: 100,
    currentStockPcs: 120,
    minStockAlert: 24,
  },
  {
    sku: 'AK-47',
    name: 'Hi5 pillow wafer Straberry-19gm',
    banglaName: 'হাই ফাইভ পিলো ওয়েফার স্ট্রবেরি ১৯ গ্রাম',
    category: 'Wafers & Rolls',
    cartonSize: 72,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 720,
    minStockAlert: 144,
  },
  {
    sku: 'AK-48',
    name: 'Hi5 Milk Wafer Poly (12gm)',
    banglaName: 'হাই ফাইভ মিল্ক ওয়েফার পলি ১২ গ্রাম',
    category: 'Wafers & Rolls',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-49',
    name: 'Hi5 Chocolate Wafer Poly (12gm)',
    banglaName: 'হাই ফাইভ চকলেট ওয়েফার পলি ১২ গ্রাম',
    category: 'Wafers & Rolls',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-50',
    name: 'Classic Chanachur (150gmx24)',
    banglaName: 'ক্লাসিক চানাচুর (১৫০গ্রাম x ২৪)',
    category: 'Chanachur & Snacks',
    cartonSize: 24,
    dealerPrice: 32.0,
    tradePrice: 36.0,
    mrp: 40,
    currentStockPcs: 240,
    minStockAlert: 48,
  },
  {
    sku: 'AK-51',
    name: 'Classic Chanachur (300gmx12)',
    banglaName: 'ক্লাসিক চানাচুর (৩০০গ্রাম x ১২)',
    category: 'Chanachur & Snacks',
    cartonSize: 12,
    dealerPrice: 62.0,
    tradePrice: 70.0,
    mrp: 75,
    currentStockPcs: 120,
    minStockAlert: 24,
  },
  {
    sku: 'AK-52',
    name: 'Classic Chanachur (90gmx48)',
    banglaName: 'ক্লাসিক চানাচুর (৯০গ্রাম x ৪৮)',
    category: 'Chanachur & Snacks',
    cartonSize: 48,
    dealerPrice: 20.0,
    tradePrice: 22.5,
    mrp: 25,
    currentStockPcs: 480,
    minStockAlert: 96,
  },
  {
    sku: 'AK-53',
    name: 'Classic Chanachur-12gm',
    banglaName: 'ক্লাসিক চানাচুর ১২ গ্রাম',
    category: 'Chanachur & Snacks',
    cartonSize: 120,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 1200,
    minStockAlert: 240,
  },
  {
    sku: 'AK-54',
    name: 'Classic Chanachur-22gm',
    banglaName: 'ক্লাসিক চানাচুর ২২ গ্রাম',
    category: 'Chanachur & Snacks',
    cartonSize: 96,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-55',
    name: 'Funtastic Cheese Bite 14gm',
    banglaName: 'ফ্যান্টাস্টিক চিজ বাইট ১৪ গ্রাম',
    category: 'Chanachur & Snacks',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-56',
    name: 'Funtastic Potato Crackers-13gm',
    banglaName: 'ফ্যান্টাস্টিক পটেটো ক্র্যাকার্স ১৩ গ্রাম',
    category: 'Chanachur & Snacks',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-57',
    name: 'Jhal Chanachur (22gmx192)',
    banglaName: 'ঝাল চানাচুর (২২গ্রাম x ১৯২)',
    category: 'Chanachur & Snacks',
    cartonSize: 192,
    dealerPrice: 8.2,
    tradePrice: 9.0,
    mrp: 10,
    currentStockPcs: 1920,
    minStockAlert: 384,
  },
  {
    sku: 'AK-58',
    name: 'Funtastic Onion Ring Chips-14gm',
    banglaName: 'ফ্যান্টাস্টিক ওনিয়ন রিং চিপস ১৪ গ্রাম',
    category: 'Chanachur & Snacks',
    cartonSize: 96,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 960,
    minStockAlert: 192,
  },
  {
    sku: 'AK-59',
    name: 'Hi5 Morf-9 gm (Cartoon Series)',
    banglaName: 'হাই ফাইভ মরফ ৯ গ্রাম (কার্টুন সিরিজ)',
    category: 'Wafers & Rolls',
    cartonSize: 120,
    dealerPrice: 4.1,
    tradePrice: 4.5,
    mrp: 5,
    currentStockPcs: 1200,
    minStockAlert: 240,
  },
];

export async function syncTanvirTradersCatalog() {
  console.log(`[Seed] Syncing exact 59 products for Tanvir Traders...`);
  // Remove existing products to cleanly reset with user's exact 59 items
  await Product.deleteMany({});

  for (const item of akijFantasticProducts) {
    await Product.create({
      ...item,
      priceHistory: [
        {
          tradePrice: item.tradePrice,
          dealerPrice: item.dealerPrice,
          effectiveFrom: new Date(),
          note: 'Tanvir Traders Official Akij Bakers Fantastic Dealership Setup',
        },
      ],
    });
  }

  console.log(`[Seed Complete] 100% synced all 59 Akij Fantastic products for Tanvir Traders!`);
}

async function runSeed() {
  const mongoURI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/tanvir_traders_akij';
  try {
    await mongoose.connect(mongoURI);
    await syncTanvirTradersCatalog();
    process.exit(0);
  } catch (error) {
    console.error('[Seed Error]:', error);
    process.exit(1);
  }
}

// If run directly
if (process.argv[1] && process.argv[1].includes('seed.ts')) {
  runSeed();
}
